Extend the version check to the tailored jira servicedesk version
voxpupuli/puppet-jira pull request #383
Opened 2021-06-15 15:34 UTC by diLLec

#### Pull Request (PR) description
The current version check does not take the JIRA servicedesk package into account. This package has an other versioning schema - see here: https://www.atlassian.com/de/software/jira/service-management/download-archives

#### This Pull Request (PR) fixes the following issues
Currently, if the following parameters are choosen to init the jira class, the output shows

`JIRA versions older than 8.0.0 are no longer supported. Please use an older version of this module to upgrade first`

```
class { 'jira':
    #
    # JIRA parameters
    version   => '4.17.0',
    product  => 'servicedesk',
...
```

2021-06-25 13:14 UTC, oranenj commented
@diLLec the change breaks if someone is installing "jira-core". I confess I don't know if that's even a valid option anymore, but you need to add it to the enum or return it to a string and then fix the version comparison logic to take that into account.

2021-06-25 13:16 UTC, oranenj requested changes
See above comment

2021-06-29 12:48 UTC, diLLec commented
Thanks @oranenj - I've added that option and the tests seam to be succeeding now.

2021-07-06 09:46 UTC, oranenj commented
I made the changes directly from Github, I think this should be good enough to fix the issue and not break API.

2021-07-06 09:46 UTC, oranenj approved these changes

2021-07-06 09:52 UTC, bastelfreak approved these changes

2021-07-06 10:39 UTC, merged